server {
  listen 8080;
  root /usr/share/nginx/html;
  server_tokens off;
  absolute_redirect off;

  gzip on;
  gzip_types text/css application/javascript application/json image/svg+xml;

  add_header Content-Security-Policy "default-src 'self'; connect-src 'self' ${IDP_ORIGIN}; base-uri 'self'; form-action 'self'; frame-ancestors 'none'" always;
  add_header X-Content-Type-Options nosniff always;
  add_header Referrer-Policy no-referrer always;

  location /api/ {
    proxy_pass http://api:8080;
  }

  location /assets/ {
    expires max;
  }

  location / {
    try_files $uri /index.html;
    expires -1;
  }
}
